name: Maven CD

on: 
 workflow_dispatch:
 release:
    types: [created]

  
jobs:
 deploy:
  runs-on: windows-latest
  steps:
    - name: Download Workflow Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: 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
        workflow: maven.yml
        repo: Aswinimurugan/maven1
        name: Package
        path: staging
