name: Maven CD

on: 
 workflow_dispatch:
 release:
    types: [created]

  
jobs:
 deploy:
  runs-on: windows-latest
  steps:
    - name: Download Workflow Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: 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
        Repository: Aswinimurugan/maven1
        Artifact name: Package
        Local path: staging
        Workflow name: maven.yml
        Workflow conclusion: success
