name: Maven CD

on: [push]

  
jobs:
 deploy:
  runs-on: [self-hosted,linux]
  steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: |
        yum install sshpass
        dnf install sshpass
      shell: bash
