name: Maven CD

on: 
 workflow_dispatch:
 release:
    types: [created]

  
jobs:
 deploy:
  runs-on: windows-latest
  steps:
    - run: ls
    - name: Download build artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Required, workflow file name or ID
        repo: ${{ github.repository }}
        workflow: maven.yml
        name: Package
        path: ${{ github.workspace }}/staging
        search_artifacts: true
        
    - run: |
        cd staging
        ls
