name: Maven CI/CD

on:
 push:
    branches: [ develop, master ]
 pull_request:
    branches: [ develop ]

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    
  publish-job:
      runs-on: windows-latest
      needs: [build_and_test]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 17
            distribution: 'temurin'
            server-id: github
            settings-path: ${{ github.workspace }}
            cache: maven
        - run: mvn -B package --file pom.xml -DskipTests
        - name: Zip artifact for deployment
          run: zip release.zip ./* -r


        - run: mkdir staging 
        - uses: actions/upload-artifact@v2
          with:
            name: release.zip
            path: staging
        - name: download artifact
          uses: actions/download-artifact@v2
          with:
            name: release.zip
            path: staging
        - name: Test artifacts download
          run: |
            cd staging
            copy \staging\* \testing\*
            ls

